# Site settings
title: Pitt HOSA
email: pitthosa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Being pre-health isn't necessarily a walk in the park,
  but we make it feel as close as possible to one! By joining
  Pitt HOSA and inviting your friends, we establish the first
  comprehensive Pre-Health community of students at the
  University of Pittsburgh.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
